# Generated by Django 5.2.5 on 2025-09-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add books'), ('can_change_book', 'Can change books'), ('can_delete_book', 'Can delete books')]},
        ),
    ]
